name: Build and deploy container app to Azure Web App - MochikaPrueba
#comment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_URL }}/mochika/app:${{ github.sha }}
        file: ./AMochika.Presentation/Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mm'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cfb8f2331ae54cc69627f65d1d453f53 }}
        images: 'registrymochika.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7ff6988a9bb74f309c21699ef671f11e | toLower}}/mochika/app:${{ github.sha }}'



